### ISSUE TITLE
Update main.py

### ISSUE THREAD

**Issue by FloSchels** [amosproj/amos2022ss01-firmware-downloader#74]
## User story
1. As a user
2. I want / need to control how many modules will be executed, how many at one time and how regularly
3. So that I can balance the load and time it takes to run 

## Acceptance criteria
* Delete __init__.py and add functionalities to main.py
* Add number_of_threads paramater to function that controls the number of threads that are executed at the same time
* Ignore modules where the igonore value in the config file is set to true
* Update Scanner so data scan is performed on a regular basis
* Usage of config file to modify individual module scraping intervals (see https://github.com/amosproj/amos2022ss01-firmware-downloader/issues/30)
* Add/Use config option to modify general scan interval

## Definition of done (DoD)
* Code is complete
* Code is uploaded in GitHub
* Fulfills the acceptance criteria in the User Story
* Documentation has been updated
* Functionality has been reviewed
* Only MIT-Licensed Libraries are used
* Create tests necessary to ensure feature is working
* Bill of Materials updated

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by FendVario1** [comment]
As mentioned in Slack:

- get_skipped_modules ignores the default config fallback.
-  Does your code really work as expected?\
Because as I see it you're creation num_threads threads and then in the threads call scanner. However a scanner thread will never stop running, as it is scheduled repeatedly without a terminating condition.\
As a result num_threads modules will be executed, all other modules will never be run.
